language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - PIP=pip
        - CIBW_MANYLINUX1_X86_64_IMAGE=safijari/manylinux-x64
        - CIBW_PLATFORM=linux
        - CIBW_SKIP="*-manylinux1_i686"
        - CIBW_ENVIRONMENT_LINUX="COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG"

script:
  - $PIP install cibuildwheel==0.10.0
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
